name: sagase_dictionary
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  drift: 2.28.0
  path: ^1.9.0
  xml: ^6.4.2
  meta: ^1.17.0
  archive: ^4.0.7
  kana_kit: ^2.1.1
  diacritic: ^0.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9

  drift_dev: any
  build_runner: any

  async: ^2.11.0
