name: sagase_dictionary
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  path: ^1.8.3
  isar: ^3.1.0+1
  xml: ^6.3.0
  meta: ^1.9.1
  archive: ^3.3.7
  kana_kit: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/kana_kit

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4

  build_runner: any
  isar_generator: any
