name: sagase_dictionary
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  drift: ^2.18.0
  path: ^1.9.0
  xml: ^6.4.2
  meta: ^1.10.0
  archive: ^3.4.9
  kana_kit: # TODO change to main one after merge
    git:
      url: https://github.com/Moseco/kana_kit

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9

  drift_dev: ^2.18.0
  build_runner: any

  async: ^2.11.0
